### ISSUE TITLE
Training app issues 

### ISSUE THREAD

**Issue by LeylaLMS** [OfficeDev/microsoft-teams-apps-training#4]
Customer has implemented the Training app and running into 3 issues:

We have 3 issues with this app currently:
1.	User completion report pop up screen comes up white. Customer is unable to see the completion report of the users and therefore it is an urgent problem.
2.	Some users who complete training doesn’t show up as completed on the report when custome was able to see the report last week. 
3.	Some user answers on quiz part of the traing correctly yet when the quiz is completed it show the answer as wrong. It doesnt happen for all users but some.

**Comment by yogesh-MS** [comment]
As discussed earlier, we have fixed the issue and merged in git hub repo.
